In [2]:
import torch
import triton

DEVICE = triton.runtime.driver.active.get_active_torch_device()

torch.manual_seed(0)
x = torch.randn(1823, 781, device=DEVICE)

In [3]:
x

tensor([[-0.9247, -0.4253, -2.6438,  ..., -0.3973, -1.4014,  0.1308],
        [ 0.1130,  0.3553, -2.0293,  ..., -1.9122, -0.3367,  0.1030],
        [ 0.5308,  0.2370,  0.7196,  ...,  0.3919, -0.0478, -0.9405],
        ...,
        [-0.1985,  0.2281,  0.0500,  ..., -0.1201,  1.0384, -0.0653],
        [ 0.2965,  1.8683,  1.3510,  ...,  2.1793,  0.5151, -1.3828],
        [ 1.3971, -0.6241,  0.2197,  ...,  2.4324,  0.2609, -1.7424]],
       device='cuda:0')

In [13]:
x_max = x.max(dim=1)[0]
x_max

tensor([3.3156, 2.7486, 3.1057,  ..., 2.7288, 3.2970, 3.7089], device='cuda:0')

In [15]:
z = x - x_max[:, None]

In [16]:
z

tensor([[-4.2403, -3.7410, -5.9595,  ..., -3.7129, -4.7170, -3.1849],
        [-2.6355, -2.3932, -4.7778,  ..., -4.6608, -3.0852, -2.6456],
        [-2.5749, -2.8687, -2.3861,  ..., -2.7138, -3.1535, -4.0462],
        ...,
        [-2.9273, -2.5007, -2.6788,  ..., -2.8490, -1.6904, -2.7941],
        [-3.0006, -1.4287, -1.9460,  ..., -1.1177, -2.7819, -4.6798],
        [-2.3117, -4.3329, -3.4891,  ..., -1.2764, -3.4479, -5.4512]],
       device='cuda:0')

In [17]:
x

tensor([[-0.9247, -0.4253, -2.6438,  ..., -0.3973, -1.4014,  0.1308],
        [ 0.1130,  0.3553, -2.0293,  ..., -1.9122, -0.3367,  0.1030],
        [ 0.5308,  0.2370,  0.7196,  ...,  0.3919, -0.0478, -0.9405],
        ...,
        [-0.1985,  0.2281,  0.0500,  ..., -0.1201,  1.0384, -0.0653],
        [ 0.2965,  1.8683,  1.3510,  ...,  2.1793,  0.5151, -1.3828],
        [ 1.3971, -0.6241,  0.2197,  ...,  2.4324,  0.2609, -1.7424]],
       device='cuda:0')

In [18]:
x.t()

tensor([[-0.9247,  0.1130,  0.5308,  ..., -0.1985,  0.2965,  1.3971],
        [-0.4253,  0.3553,  0.2370,  ...,  0.2281,  1.8683, -0.6241],
        [-2.6438, -2.0293,  0.7196,  ...,  0.0500,  1.3510,  0.2197],
        ...,
        [-0.3973, -1.9122,  0.3919,  ..., -0.1201,  2.1793,  2.4324],
        [-1.4014, -0.3367, -0.0478,  ...,  1.0384,  0.5151,  0.2609],
        [ 0.1308,  0.1030, -0.9405,  ..., -0.0653, -1.3828, -1.7424]],
       device='cuda:0')

In [21]:
x.stride()

(781, 1)